sonar.projectKey=mern-microservices
sonar.projectName=MERN Microservices Application
sonar.projectVersion=1.0.0
sonar.sources=backend,frontend/src
sonar.exclusions=**/node_modules/**,**/coverage/**,**/*.test.js,**/test-results/**,frontend/public/**
sonar.tests=backend/user-service/tests,backend/category-service/tests,backend/product-service/tests,backend/gateway-service/tests,frontend/src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx
sonar.javascript.lcov.reportPaths=backend/user-service/coverage/lcov.info,backend/category-service/coverage/lcov.info,backend/product-service/coverage/lcov.info,backend/gateway-service/coverage/lcov.info
sonar.testExecutionReportPaths=backend/user-service/test-results/junit.xml,backend/category-service/test-results/junit.xml,backend/product-service/test-results/junit.xml,backend/gateway-service/test-results/junit.xml
sonar.sourceEncoding=UTF-8
